joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

# Position Controllers ---------------------------------------

phantom_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
   - joint_1
   - joint_2
   - joint_3
   - joint_4
   - gripper_1
   - gripper_2 
